project_id = "zqujcxgnelnzxzpfykxn"

[functions.send-reminder]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.approve-quotation]
verify_jwt = false

[functions.migrate-customers]
verify_jwt = false