// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqujcxgnelnzxzpfykxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxdWpjeGduZWxuenh6cGZ5a3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NzM0MDgsImV4cCI6MjA3NjI0OTQwOH0.B0GMdr29Gc8JHoUQxbt6wKXex1rshkoej7l-_lekHKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public'
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'garden-job-flow'
    }
  }
});