// This file is automatically generated. Do not edit it directly.
// Re-export from the main supabase client to ensure single instance
import type { Database } from './types';

export { supabase, cleanupSupabase } from '@/lib/supabase';
export type { Database };