// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyiuojjaownbvouffqbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5aXVvamphb3duYnZvdWZmcWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjAzNjEsImV4cCI6MjA3NDYzNjM2MX0.tGvHE0nlI9CM7Lf2U1uAvtZtilgvegsRruax4NBSHno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});